version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 502458678542.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - docker build -t youtubenew .
      - docker tag youtubenew:latest 502458678542.dkr.ecr.ap-south-1.amazonaws.com/youtubenew:latest
  post_build:
    commands:
      - docker push 502458678542.dkr.ecr.ap-south-1.amazonaws.com/youtubenew:latest
      - printf '[{"name":"dockerTaskDefinition","imageUri":"%s"}]' 502458678542.dkr.ecr.ap-south-1.amazonaws.com/youtubenew:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
